### ISSUE TITLE
[erpnext.com] New Pricing Update on the Website

### ISSUE THREAD

**Issue by ghost** [frappe/design#13]
- [ ] Remove P100 user plan
- [ ] Design display of P5 plan and Enterprise plan, without card. but it will include the pointers. $168/month.
- [ ] Add pricing of $10,000/year for the Enterprise plan. It will include priority support for functional queries, bug fixes, upgrades and optimisation related query. We can also indicate a point for the community-driven development.

reported by @umairsy

**Comment by raghukamath** [comment]
issue discussion at
