### ISSUE TITLE
Logo porposal

### ISSUE THREAD

**Issue by 0relmely** [frappe/design#2]
Hey thankss for your project ..!!!

I maked a proposal for corporate image you can see here ..
https://steemit.com/utopian-io/@orelmely/proposal-logo-for-frappe-charts-open-source-charts-maker

Blessings!!

**Comment by ghost** [comment]
Hey! thank you very much for the proposal and the efforts. However we already have a logo for the project, you can take a look at the logo's here https://github.com/frappe/design/tree/master/logos. 

We will update the contribution process in the readme to make it easy for people to contribute without duplicating the efforts. 

Thank you
